[terminal]
vt = 1

[default_session]
command = "/usr/local/bin/tuigreet --time --user-menu --remember --remember-session --theme 'border=brightmagenta;text=white;time=brightmagenta;container=black;title=brightmagenta;greet=white;prompt=brightmagenta;input=brightwhite;action=cyan;button=brightblue' --cmd sway"
user = "greeter"
